CREATE TABLE IF NOT EXISTS DEPARTMENT (
  EMPLOYEE_ID TEXT,
  NAME TEXT,
  DEPARTMENT_ID,
  MANAGER_ID,
  SALARY REAL
);

INSERT INTO DEPARTMENT( EMPLOYEE_ID, NAME, DEPARTMENT_ID, MANAGER_ID, SALARY ) VALUES
 ( '100', 'STEVEN KING', '90', '100', 24000 ),
 ( '101', 'NEENA KONGCAR', '90', '100', 17000 ),
 ( '102', 'LEX DAHAAN', '90', '102', 9000 ),
 ( '103', 'BRUCE LEE', '60', '103', 4800 ),
 ( '104', 'DIANA WILLS', '60', '103', 25000 ),
 ( '105"',  'LUV NAMI', '60', '102', 5000),
 ( '1975', 'VALLI PUR', '50', '100', 4200);
 
SELECT * FROM DEPARTMENT;

SELECT DEPARTMENT_ID AS "Department Code",
COUNT ( *) AS "No of Employees"
FROM DEPARTMENT
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, SUM(salary)
FROM DEPARTMENT
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID AS "Department Code",
COUNT ( *) AS "No of Employees",
SUM(salary) AS "Total_Salary"
FROM DEPARTMENT
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, COUNT(*) AS "No of Employees"
FROM DEPARTMENT
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) > 2;
