CREATE TABLE IF NOT EXISTS NOBEL_WIN (
    YEAR INTEGER,
    SUBJECT TEXT,
    WINNER TEXT,
    COUNTRY TEXT,
    CATEGORY TEXT 
    );

INSERT INTO NOBEL_WIN ( YEAR, SUBJECT, WINNER, COUNTRY, CATEGORY ) VALUES

    ( 1998, 'PHYSICS', 'HANNES ALFREND', 'TURKEY', 'SCIENTIST' ),
    ( 1975, 'MATHEMATICS', 'ALBERT HAMMINGTON', 'GERMANY', 'SCIENTIST' ),
    ( 1986, 'PHYSICS', 'WILLTON HEMMINGWAY', 'IRELAND', 'SCIENTIST' ),
    ( 1899, 'PHILOSOPHY', 'AINZ MARTINEE', 'LONDON', 'PHILOSOPHER' ),
    ( 1881, 'BIOLOGY', 'LOIS LANE', 'AMERICA', 'SCIENTIST' ),
    ( 1897, 'LITERATURE', 'MERRY LANE', 'AMERICA', 'ECONOMIST' ),
    ( 1973, 'BIOLOGY', 'PHILIPS', 'AFRICA', 'PRIME MINISTER' ),
    ( 1980, 'BIOLOGY', 'MARTIN', 'AFRICA', 'PRESIDENT' ),
    ( 1981, 'PHYSIOLOGY', 'HANNAH', 'HUNGARY', 'SCIENTIST'),
    ( 1975, 'PHYSICS', 'PETER', 'CHILE', 'SCIENTIST' );


SELECT *
FROM NOBEL_WIN
WHERE SUBJECT NOT LIKE 'P%';
