-- NOT NULL IS USED FOR NAME SO IT CAN ENSURE THAT EVERY STUDENT HAVE A NAME
CREATE TABLE IF NOT EXISTS STUDENT ( 
    ROLL_NO TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    ADDRESS TEXT,
    PHONE TEXT,
    AGE INTEGER 
);

-- INSERT SAMPLE DATA INTO THE STUDENTS TABLE
INSERT INTO STUDENT (ROLL_NO, NAME, ADDRESS, PHONE, AGE )VALUES
    ('1', 'RAM', 'DELHI', '*******', 18 ),
    ('2', 'REM', 'MALAYSIA', '********', 18 ),
    ('3', 'RAMESH', 'INDIA', '********', 20 ),
    ('4', 'SURESH', 'AMERICA', '*********', 19 ),
    ('5', 'JAMAL' , 'JAMICA', '********', 17 );
    
-- SELECT ALL RECORDS FROM THE SALESMAN TALBE TO VERIFY INSERTION 
SELECT * FROM Salesman;

-- SELECT ALL RECORDS FROM THE STUDENT TO VERIFY
SELECT * FROM STUDENT;

-- QUERY STUDENTS WHO ARE 18 YEAR OLD AND LIVE IN DELHI
SELECT * FROM STUDENT WHERE AGE = 18 AND ADDRESS = 'DELHI';

-- QUERY STUDENTS WHO ARE 18 AND NAMED RAM
SELECT * FROM STUDENT WHERE AGE = 18 AND NAME = 'RAM';

-- QUERY STUDENTS WHO ARE NAMED RAM OR RAMESH
SELECT * FROM STUDENT WHERE NAME = 'RAM' OR NAME = 'RAMESH';

-- QUERY STUDENTS NAMED RAM OR AGE 20
SELECT * FROM STUDENT WHERE NAME = 'RAM' OR AGE = 20;

-- QUERY STUDENTS OF AGE 18 AND NAMED RAM OR SURESH
SELECT * FROM STUDENT WHERE AGE = 18 AND NAME = 'RAM' OR NAME = 'SURESH';

